version: 0.2

phases:
  build:
    commands:
      - aws deploy push --application-name hands-on-app --s3-location s3://20240802cicd/artifact.zip --source src
artifacts:
  files:
    - '**/*'
  base-directory: src